const types = {
  TEAM_1_UNITS_CHANGE: 'TEAM_0_UNITS_CHANGE',
  TEAM_2_UNITS_CHANGE: 'TEAM_1_UNITS_CHANGE',
  CURRENT_TEAM_CHANGE: 'CURRENT_TEAM_CHANGE',
  CURRENT_UNIT_CHANGE: 'CURRENT_USER_CHANGE',
  ORDER_TEAM_CHANGE: 'ORDER_TEAM_CHANGE',
};

export default types;
