const types = {
  UNITS_CHANGE: 'UNITS_CHANGE',
  ONE_UNIT_CHANGE: 'ONE_UNIT_CHANGE',
  CHOSEN_UNIT_INDEX_CHANGE: 'CHOSEN_UNIT_INDEX_CHANGE',
  CURRENT_UNIT_INDEX_CHANGE: 'CURRENT_UNIT_INDEX_CHANGE',
  NEXT_GAME_TICK: 'NEXT_GAME_TICK',
  RESTART_GAME_TICK: 'RESTART_GAME_TICK',
  CURRENT_TEAM_CHANGE: 'CURRENT_TEAM_CHANGE',
  CURRENT_UNIT_CHANGE: 'CURRENT_USER_CHANGE',
  ORDERED_TEAM_CHANGE: 'ORDERED_TEAM_CHANGE',
};

export default types;
