const types = {
  UNITS_CHANGE: 'UNITS_CHANGE',
  CURRENT_UNIT_INDEX_CHANGE: 'CURRENT_UNIT_INDEX_CHANGE',
  CURRENT_TEAM_CHANGE: 'CURRENT_TEAM_CHANGE',
  CURRENT_UNIT_CHANGE: 'CURRENT_USER_CHANGE',
  ORDERED_TEAM_CHANGE: 'ORDERED_TEAM_CHANGE',
};

export default types;
